export function emptyProposalData() {
  return {
    prospectRecordId: null,
    proposalDate: new Date().toISOString().split('T')[0],
    validUntil: '',
    studentName: '',
    email: '',
    phone: '',
    nationality: '',
    studentProfile: {
      currentStatus: '',
      academicLevel: '',
      obtainedDiploma: [],
      academicRecords: [],
      academicDescription: '',
      fieldOfPreviousStudies: '',
      yearOfGraduation: '',
      currentOccupation: '',
      languages: [],
      languageRecords: [],
      languageDescription: '',
      note: '',
    },
    studyPreferences: {
      targetDegreeLevel: '',
      intendedIntake: '',
      fieldOfStudyPrimary: '',
      alternativeField: '',
      programLanguages: [],
      financingPlan: '',
      blockedAccount: '',
      hasAbroadSupport: '',
      abroadSupportDetails: '',
      financialGuarantor: '',
      projectBudget: '',
      cityPreferenceType: '',
      preferredCityUniversity: '',
    },
    services: { selected: [], note: '' },
  };
}
